services:
  test:
    image: maven:3.9.11-eclipse-temurin-21
    working_dir: /app
    volumes:
      - .:/app
    command: ["mvn", "clean", "test", "--no-transfer-progress", "-B"]
    container_name: go-con-coche-test
    environment:
      - SPRING_PROFILES_ACTIVE=test
    restart: no