services:
  go-con-coche-db:
    image: mysql:8.0
    container_name: go-con-coche-db
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER_DOCKER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD_DOCKER}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-uroot", "-p${DB_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 20
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - go-con-coche-network

  go-con-coche-app:
    image: go-con-coche-app
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-con-coche-app
    env_file:
      - .env
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    environment:
      DB_USERNAME: ${MYSQL_USER_DOCKER}
      DB_PASSWORD: ${MYSQL_PASSWORD_DOCKER}
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - go-con-coche-db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"] # Health check command
      interval: 30s # Check every 30 seconds
      timeout: 10s # Timeout after 10 seconds
      retries: 3 # Retry 3 times before marking as unhealthy
      start_period: 60s
    networks:
      - go-con-coche-network

networks:
  go-con-coche-network:
    driver: bridge
    name: go-con-coche-network

volumes:
  mysql_data:
    name: go-con-coche_mysql_data
  app_logs:
    name: go-con-coche_app_logs
