spring:
  output:
    ansi:
      enabled: ALWAYS
  application:
    name: go_con_coche
  config:
    import: optional:file:.env[.properties]

  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false

  datasource:
    url: ${DB_URL_LOCAL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    root-password: ${DB_ROOT_PASSWORD}

  sql:
    init:
      mode: always

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

server:
  port: ${SERVER_PORT:8080}

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}

jwt:
  rsa-public-key: ${RSA_PUBLIC_KEY}
  rsa-private-key: ${RSA_PRIVATE_KEY}