apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    tier: backend
spec:
  replicas: 4
  selector:
    matchLabels:
      tier: backend
  template:
    metadata:
      labels:
        tier: backend
    spec:
      containers:
        - name: app
          image: fyrfigrabbaf6kyhpi/go-con-coche:latest
          ports:
            - containerPort: 8080
              name: http
          envFrom:
            - secretRef:
                name: mail-config
            - secretRef:
                name: jwt-config
            - secretRef:
                name: cloudinary-config

          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "kubernetes"
            - name: SERVER_PORT
              value: "8080"
            - name: MYSQL_URL
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: db-url
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: database-credentials
                  key: username
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-credentials
                  key: password
            - name: SHOW_SQL
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: show-sql
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3